### PR TITLE
fix filename long

### PR DESCRIPTION
**Pull request by nopeless**

### CODE REVIEW

**Comment by nopeless** [comment]
I am about to throw myself as this has to be some kind of elaborate joke

Why did you think it was a good idea to have `song_name` and `filename` redundant

**Comment by nopeless** [comment]
@jsavargas If you have some time, can you merge this soon? I added a lint commit as well which formats using Black, the famous Python linter

**Comment by scarlettekk** [comment]
should using Black possibly be a different PR? I agree that a formatter is needed, but the huge diff makes it hard to see what actually changed in the code's logic versus just format changes

**Comment by nopeless** [comment]
> should using Black possibly be a different PR? I agree that a formatter is needed, but the huge diff makes it hard to see what actually changed in the code's logic versus just format changes

Can you push a Black format push yourself to master? Then the diff will just include the logic changes
@scarlettekk

**Comment by scarlettekk** [comment]
> > should using Black possibly be a different PR? I agree that a formatter is needed, but the huge diff makes it hard to see what actually changed in the code's logic versus just format changes
> 
> Can you push a Black format commit yourself to master? Then the diff will just include the logic changes @scarlettekk

I can make a PR for it, but I don't have push access to master - I've just written a PR in the past.

**Comment by jsavargas** [comment]
I have been with many personal things and I have put this aside, maybe at night I start to review the PR to accept them and see how I can continue advancing, this has had more impact than I thought at the time: P

**Pull request merged**
