### PR TITLE
emulate realtime downloading

### PR DESCRIPTION
**Pull request by EDad-v2**
Emulate the time it takes to play a music track between multi-track downloads.
Track duration is scraped.
Download, encoding, and tagging time are subtracted from duration. Then the remaining seconds are displayed in a countdown message while sleeping.

```
Harry Connick, Jr. - What A Night! A Christmas Album - Have a Holly Jolly Christmas.mp3: 100%|█████████▉| 4.32M/4.32M [00:03<00:00, 1.20MB/s]
Emulating playing track in realtime. Resuming in 0:03:22 ...
```

For the paranoid.

### CODE REVIEW

**Comment by EDad-v2** [comment]
Changed to draft. There's two pull requests not merged that cause conflict. I'll rework this one if and when the others are merged.

**Comment by scarlettekk** [comment]
Would this actually look any less suspicious on Spotify's end, or would we need to actually throttle the download hard enough that it takes that long....

**Comment by EDad-v2** [comment]
> Would this actually look any less suspicious on Spotify's end, or would we need to actually throttle the download hard enough that it takes that long... I wonder if there's a way to determine that

That's a good question. I "believe" completely avoiding detection on Spotify's end is likely impossible. The api allows for setting volume control on a remote client. Surely they can tell when a user is not using a proper client.
I'm far from a streaming expert, but usually the entire music file is not available in one go. The url's usually point to a small bit of the overall music file, and the client "stitches" them together for our listening pleasure. librespot goes gangbusters and sends the decoded stream to us. I was thinking if we put a wait timer in the while loop where the request is sent, we could use the bitrate and our chunk size to slow down the loop. But do those chunks match what a actual client grabs? While playing a Spotify song using the web browser, I hit airplane mode to kill my internet. The song stopped playing within seconds. I'd guess what is buffered is very small.

At least waiting the duration of the song before attempting to grab another before it's impossible to listen to it would be "something".  Spotify's api is out there to allow 3rd party clients to get music, maybe they've allowed a bit of wiggle rooms to those clients as long as they aren't obviously mirroring Spotify servers? 
*shrug*

Maybe librespot has some sort of parameter to slow down downloads?  I've dug around in the code and quickly discovered I have much to learn before understanding it :package: 
I wish they had more docs.

**Comment by scarlettekk** [comment]
Looks great, very stealthy! I know next to nothing about spotify's API, so this is very impressive to me as someone who just builds crazy ass ffmpeg commands in their spare time.

**Pull request closed without merging**
