### PR TITLE
Fix percent in progress bar and fix migration message when migration does`t start

### PR DESCRIPTION
**Pull request by Bionded**
Fix percent in progress bar and fix migration message when migration does`t start

### CODE REVIEW

**Comment by nicknitewolf** [comment]
I realised that os.path uses str to make paths, inconsistent between unix and windows paths. Could we use pathlib.Path instead? currently its used for credentials already.

Currently archive records as:
```
C:\\Users\\Nicholas/Music/ZSpotify Music\\...\\...
```

**Comment by Bionded** [comment]
I think we can. Maybe we also can use abs pathes, but it's need test. Maybe on next week i will test and choise a better wvariant

**Comment by nicknitewolf** [comment]
> I think we can. Maybe we also can use abs pathes, but it's need test. Maybe on next week i will test and choise a better wvariant

Alright nice, I wanted to make m3u playlist function today but the paths were making the testing hard

**Comment by Bionded** [comment]
I don't think it's good idea. Mybe need release new version and after add new features?
My plan:
1) fix all bugs in these release
2) change versioning
    2.0.0 -base release
    2.0.x -minor releases - bugfixing
    2.x.0 - major releases - with new faetures or changing logic
3) add availability to create new branches for approved maintainers
4) release 2.0.0
5) create branch 2.0.1 and from this branch create new patches with bugfixing
6) create new feature branch (2.1.0)where we add new features and merging all fixes from minor releases
7) create list with feature request , and possible upgrades
8) make this thing are real
9) ???
10) Profit

**Comment by nicknitewolf** [comment]
> I don't think it's good idea. Mybe need release new version and after add new features? My plan:
> 
> 1. fix all bugs in these release
> 2. change versioning
>    2.0.0 -base release
>    2.0.x -minor releases - bugfixing
>    2.x.0 - major releases - with new faetures or changing logic
>    all versions can be more than 9 like: 2.0.11 or 2.13.6
> 3. add availability to create new branches for approved contributors
> 4. release 2.0.0
> 5. create branch 2.0.1 and from this branch create new patches with bugfixing
> 6. create new feature branch (2.1.0)where we add new features and merging all fixes from minor releases
> 7. create list with feature request , and possible upgrades
> 8. make this thing are real
> 9. ???
> 10. Profit

Wiki page would be nice too. Also could you check my #76

**Comment by Bionded** [comment]
Sorry guys, i left for a week. Near my house exploded f@ckin Shahed. No time to develop for now

**Comment by jsavargas** [comment]
> Sorry guys, i left for a week. Near my house exploded f@ckin shahed. No time to develop for now

How's it going with the explosion?  I hope you are well with your loved ones

**Comment by Bionded** [comment]
Thank you friend :). For now, we have no more exploses nearby a week. Strange, evcery day waiting for more. For this year I got used to the missiles and explosions.
Need one more day and going fix some  my shitty code and add new commets :)
You said you created a discord server for develop and help? Can you link it or add me "Bionded#2350"?

**Comment by jsavargas** [comment]
https://discord.gg/FdJMau8sf6

**Pull request merged**
