### PR TITLE
Reimplement select playlist with smarter parser

### PR DESCRIPTION
**Pull request by nicknitewolf**

### CODE REVIEW

**Comment by Bionded** [comment]
looks good, but can't test now,tommorow can test

**Comment by jsavargas** [comment]
I love how they have been adding substantial improvements to this project, I will check if this change is safe, and if Bionded doesn't bother and we add it, I await your confirmation

**Comment by Bionded** [comment]
Of course add if it's working) It's realy good idea)
Sorry, for a week i can't test.

**Comment by jsavargas** [comment]
I made a discord, if you feel more comfortable throwing out ideas, if you want, I'll leave the link here

**Pull request merged**
